// Command oracle is a runnable demo of golem against a real Oracle
// database, using the User/Post/Category/PostToCategory entities declared
// in entities.go.
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/leandroluk/golem"
	"github.com/leandroluk/golem/driver/oracle"
	"github.com/leandroluk/golem/internal/op"
	"github.com/leandroluk/golem/internal/query"
	"github.com/leandroluk/golem/internal/repository"
)

const defaultDSN = "oracle://system:Golem_Test_2026@localhost:51521/FREEPDB1"

func resolveDSN() string {
	if dsn := os.Getenv("GOLEM_ORACLE_TEST_DSN"); dsn != "" {
		return dsn
	}
	return defaultDSN
}

func mustValue[V any](v V, err error) V {
	if err != nil {
		panic(err)
	}
	return v
}

func mustExec(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
	dsn := resolveDSN()
	dataSource := mustValue(golem.NewDataSource(oracle.New(func(o *oracle.Options) { o.DSN = dsn })))
	mustExec(dataSource.Connect())
	defer dataSource.Close()

	fmt.Println("Connected to Oracle.")
	ctx := context.Background()

	// Run migration statements split by /
	migrationStmts := []string{
		`BEGIN EXECUTE IMMEDIATE 'DROP TABLE "post_to_category"'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`,
		`BEGIN EXECUTE IMMEDIATE 'DROP TABLE "post"'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`,
		`BEGIN EXECUTE IMMEDIATE 'DROP TABLE "category"'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`,
		`BEGIN EXECUTE IMMEDIATE 'DROP TABLE "users"'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;`,
		`CREATE TABLE "users" ("id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, "name" VARCHAR2(50) NOT NULL, "email" VARCHAR2(50) NOT NULL)`,
		`CREATE TABLE "post" ("id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, "owner_user_id" NUMBER NOT NULL, "title" VARCHAR2(50) NOT NULL, "content" CLOB NOT NULL, FOREIGN KEY ("owner_user_id") REFERENCES "users"("id"))`,
		`CREATE TABLE "category" ("id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, "name" VARCHAR2(50) NOT NULL)`,
		`CREATE TABLE "post_to_category" ("post_id" NUMBER NOT NULL, "category_id" NUMBER NOT NULL, PRIMARY KEY ("post_id", "category_id"), FOREIGN KEY ("post_id") REFERENCES "post"("id"), FOREIGN KEY ("category_id") REFERENCES "category"("id"))`,
	}
	for _, stmt := range migrationStmts {
		mustValue(dataSource.Exec(ctx, stmt))
	}

	user := mustValue(repository.Get(dataSource, UserEntity).Insert(ctx, &User{
		Name:  "John Doe",
		Email: "john.doe@email.com",
	}))

	fmt.Printf("Inserted user: %+v\n", user)

	posts := mustValue(repository.Get(dataSource, PostEntity).InsertMany(ctx,
		&Post{OwnerUserID: user.ID, Title: "Hello, Golem!", Content: "My first post using golem."},
		&Post{OwnerUserID: user.ID, Title: "A Second Post", Content: "Another post, still using golem."},
	))
	fmt.Printf("Inserted %d posts: %+v\n", len(posts), posts)

	categories := mustValue(repository.Get(dataSource, CategoryEntity).InsertMany(ctx,
		&Category{Name: "Announcements"},
		&Category{Name: "Tutorials"},
	))
	fmt.Printf("Inserted %d categories: %+v\n", len(categories), categories)

	postToCategories := mustValue(repository.Get(dataSource, PostToCategoryEntity).InsertMany(ctx,
		&PostToCategory{PostID: posts[0].ID, CategoryID: categories[0].ID},
		&PostToCategory{PostID: posts[1].ID, CategoryID: categories[1].ID},
	))
	fmt.Printf("Inserted %d post-to-category links: %+v\n", len(postToCategories), postToCategories)

	foundUser := mustValue(repository.Get(dataSource, UserEntity).FindOne(ctx, func(u *User, q *query.Query[User]) {
		q.Where(op.Eq(&u.ID, user.ID))
	}))
	fmt.Printf("Round-trip FindOne(user.ID=%d) => %+v\n", user.ID, foundUser)
	fmt.Println("Done.")
}
