networks:
  golem:
    name: golem

services:
  golem-postgres:
    image: postgres
    container_name: golem-postgres
    networks: [ golem ]
    ports: [ "${DOCKER_POSTGRES_PORT:?DOCKER_POSTGRES_PORT is required}:5432" ]
    environment:
      POSTGRES_USER: "${DOCKER_POSTGRES_USERNAME:?DOCKER_POSTGRES_USERNAME is required}"
      POSTGRES_PASSWORD: "${DOCKER_POSTGRES_PASSWORD:?DOCKER_POSTGRES_PASSWORD is required}"
      POSTGRES_DB: "${DOCKER_POSTGRES_DATABASE:?DOCKER_POSTGRES_DATABASE is required}"
    volumes: [ "./.docker/postgres:/var/lib/postgresql/data" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DOCKER_POSTGRES_USERNAME}" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
